deprecated replacements section removed
keikoproj/addon-manager pull request #189
Opened 2023-01-18 06:07 UTC by anushkabishnoi

2023-01-18 19:23 UTC, kevdowney commented
Hi @anushkabishnoi Thanks for this PR, you'll need to sign the DCO and use signed commits, so this PR will need to be resubmitted.

2023-01-18 19:28 UTC, kevdowney requested changes

2023-01-18 19:28 UTC, kevdowney commented on .goreleaser.yml
> +archives:
Hey so we don't need this section at all, I'll comment above what we need todo.

2023-01-18 19:28 UTC, kevdowney commented on .goreleaser.yml
>      name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
```suggestion
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
```

2023-01-19 07:39 UTC, anushkabishnoi commented
> Hi @anushkabishnoi Thanks for this PR, you'll need to sign the [DCO](https://github.com/keikoproj/addon-manager/pull/189/checks?check_run_id=10717472466) and use signed commits, so this PR will need to be resubmitted.

Okay so do I close this one, and then create another pr, via CLI with the sign-off, right?

2023-01-19 17:30 UTC, closed without merging